// Command genfont generates font/hangul_data.go from the Dalmoori TTF.
package main

import (
	"fmt"
	"image"
	"os"
	"sort"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

const (
	hangulStart = 0xAC00
	hangulEnd   = 0xD7A3
	fontSize    = 8
	imgSize     = 16 // render into a larger canvas to capture the glyph
)

func main() {
	ttfData, err := os.ReadFile("font/dalmoori.ttf")
	if err != nil {
		fmt.Fprintf(os.Stderr, "reading font: %v\n", err)
		os.Exit(1)
	}

	ft, err := opentype.Parse(ttfData)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing font: %v\n", err)
		os.Exit(1)
	}

	face, err := opentype.NewFace(ft, &opentype.FaceOptions{
		Size:    fontSize,
		DPI:     72,
		Hinting: font.HintingFull,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "creating face: %v\n", err)
		os.Exit(1)
	}
	defer face.Close()

	glyphs := make(map[rune][8]byte)

	for r := rune(hangulStart); r <= hangulEnd; r++ {
		bmp := renderGlyph(face, r)
		if bmp != ([8]byte{}) {
			glyphs[r] = bmp
		}
	}

	if err := writeOutput(glyphs); err != nil {
		fmt.Fprintf(os.Stderr, "writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %d Hangul glyphs\n", len(glyphs))
}

// renderGlyph rasterizes a single rune and returns an 8-column bitmap.
// Each byte is one column; bit 0 = top row, bit 7 = bottom row.
func renderGlyph(face font.Face, r rune) [8]byte {
	img := image.NewGray(image.Rect(0, 0, imgSize, imgSize))

	d := &font.Drawer{
		Dst:  img,
		Src:  image.White,
		Face: face,
		Dot:  fixed.P(0, fontSize), // baseline at y=fontSize
	}

	d.DrawString(string(r))

	// Convert the 8x8 top-left region to column-based format.
	var cols [8]byte
	for col := 0; col < 8; col++ {
		var b byte
		for row := 0; row < 8; row++ {
			px := img.GrayAt(col, row).Y
			if px > 127 {
				b |= 1 << uint(row)
			}
		}
		cols[col] = b
	}
	return cols
}

func writeOutput(glyphs map[rune][8]byte) error {
	f, err := os.Create("font/hangul_data.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/genfont; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package font")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var hangulFont = map[rune][8]byte{")

	// Sort keys for deterministic output.
	runes := make([]rune, 0, len(glyphs))
	for r := range glyphs {
		runes = append(runes, r)
	}
	sort.Slice(runes, func(i, j int) bool { return runes[i] < runes[j] })

	for _, r := range runes {
		g := glyphs[r]
		fmt.Fprintf(f, "\t%q: {0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X},\n",
			r, g[0], g[1], g[2], g[3], g[4], g[5], g[6], g[7])
	}

	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	return nil
}
